#!/usr/bin/python3

import json
import sys
 
data = json.load(sys.stdin)

for element in data:
    if "tagName" in element and element["tagName"] == "dl":
        print (json.dumps(element, sort_keys=True, indent=4))


