#!/bin/bash

#add mycouchdb as alias of localhost
augtool -b -s \
  set '/files/etc/hosts/*[ipaddr="127.0.0.1"]/alias[.="mycouchdb"]' 'mycouchdb'
  set '/files/etc/hosts/*[ipaddr="127.0.0.1"]/alias[.="bookmarkdb"]' 'bookmarkdb'

