#!/bin/bash

#add mycouchdb as alias of localhost
augtool -b '
  set /files/etc/hosts/01/ipaddr 127.0.0.3
  set /files/etc/hosts/*[ipaddr="127.0.0.3"]/canonical[.="mycouchdb"] mycouchdb
  set /files/etc/hosts/*[ipaddr="127.0.0.3"]/alias[.="bookmarkdb"] bookmarkdb
  save
'

