#!/bin/bash

cd "$(dirname "$0")"/.
host_base_dir="$(pwd)"
cd -

function start-couchdb {
    data_on_host="${host_base_dir}/data1"
    data_in_docker="/usr/local/var/lib/couchdb"
    config_on_host="${host_base_dir}/config1"
    config_in_docker="/usr/local/etc/couchdb/local.d"
    multi_host_network="attachable-multi-host-network"
    sudo --group docker \
        docker run --rm --name my-couchdb1 \
	    -p 127.0.0.3:80:5984 \
	    -v "${data_on_host}":"${data_in_docker}" \
	    -v "${config_on_host}":"${config_in_docker}" \
            --network "${multi_host_network}" \
	    couchdb:1
}

start-couchdb
